version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.0-dev.20210125
    - 4.2.0-dev.20210201
    - 4.2.0-dev.20210208
    - 4.3.0-dev.20210215
    - 4.3.0-dev.20210222
    - 4.3.0-dev.20210228
    - 4.3.0-dev.20210308
    - 4.3.0-dev.20210315
    - 4.3.0-dev.20210322
    - 4.3.0-dev.20210329
    - 4.3.0-dev.20210405
    - 4.3.0-dev.20210412
  - dependency-name: "@types/node"
    versions:
    - 10.17.51
    - 10.17.52
    - 10.17.54
    - 10.17.55
    - 10.17.56
  - dependency-name: mime
    versions:
    - 2.5.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  target-branch: ts-issue-global-demo
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.0-dev.20210125
    - 4.2.0-dev.20210201
    - 4.2.0-dev.20210208
    - 4.3.0-dev.20210215
    - 4.3.0-dev.20210222
    - 4.3.0-dev.20210228
    - 4.3.0-dev.20210308
    - 4.3.0-dev.20210315
    - 4.3.0-dev.20210322
    - 4.3.0-dev.20210329
    - 4.3.0-dev.20210405
    - 4.3.0-dev.20210412
  - dependency-name: "@types/node"
    versions:
    - 10.17.51
    - 10.17.52
    - 10.17.54
    - 10.17.55
    - 10.17.56
  - dependency-name: mime
    versions:
    - 2.5.0
